### ISSUE TITLE
Create Index of Library Best Bets 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/allsearch_rails_api#36]
### User story
As a developer I would like to populate an index of Library Best Bet content so I can implement a allsearch service that searches this data. 

###
Current best bet content (extracted from the Drupal website) is at https://docs.google.com/spreadsheets/d/1UJehce_Bcamist3Y5V80LvhfWVbrMvQtxaIy_jGQjks/edit#gid=170493948. 

### Tasks

- [x] Create new database table that can store library best content for search. 
- [x] Load the data from the the Google Doc that public services staff maintain see issue ([Load task](https://github.com/pulibrary/allsearch_rails_api/issues/37)).
- [x] Index keyword fields (Title, Description, URL, Search Terms). 
- [x] Query this data in the context of the service implemented in issue number (fill in)
